package me.events;

public enum TipEveniment {
    USER_ADDED, DATE_LOGARE, SARCINA_DELETE, SARCINA_NOUA, SARCINA_COMPLETATA, CERERE_ADD_FEEDBACK, FEEDBACK_ADDED, LOAD_FORM_DESCRIERE, ANGAJAT_LOGAT, SARCINA_UPDATE
}
